# Change these first
owner: Adsenser # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 스팟 다모앗
    url: https://spot.damoat.com/
  - name: 주소 API
    url: https://madefor.github.io/postal-code-api/api/v1/350/1106.json

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Adsenser
  introTitle: "**실시간** 모니터링"
  introMessage: 일정시간마다 사이트의 다운 여부와 핑을 체크합니다.
  navbar:
    - title: 상태
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
